CREATE TABLE ZOO_CONTRACTORS(
   CONTRACTOR_ID      NUMBER (3, 0) NOT NULL
  ,CONTRACTOR_NAME    VARCHAR(12) NOT NULL
  ,CONTRACTOR_ADDRESS VARCHAR(29) NOT NULL
  ,CONTRACTOR_CITY    VARCHAR(9) NOT NULL
  ,CONTRACTOR_STATE   VARCHAR(14) NOT NULL
  ,CONTRACTOR_ZIP     NUMBER (5) NOT NULL
  ,CONTRACTOR_PHONE   VARCHAR(12) NOT NULL
  ,constraint contractor_id_pk PRIMARY KEY (contractor_id)
);
INSERT INTO ZOO_CONTRACTORS(CONTRACTOR_ID,CONTRACTOR_NAME,CONTRACTOR_ADDRESS,CONTRACTOR_CITY,CONTRACTOR_STATE,CONTRACTOR_ZIP,CONTRACTOR_PHONE) VALUES (501,'Zoonder','282 Eastwood Point','Denver','Colorado',80228,'303-698-2325');
INSERT INTO ZOO_CONTRACTORS(CONTRACTOR_ID,CONTRACTOR_NAME,CONTRACTOR_ADDRESS,CONTRACTOR_CITY,CONTRACTOR_STATE,CONTRACTOR_ZIP,CONTRACTOR_PHONE) VALUES (502,'Quimm','4981 Grim Lane','Atlanta','Georgia',31190,'404-875-9906');
INSERT INTO ZOO_CONTRACTORS(CONTRACTOR_ID,CONTRACTOR_NAME,CONTRACTOR_ADDRESS,CONTRACTOR_CITY,CONTRACTOR_STATE,CONTRACTOR_ZIP,CONTRACTOR_PHONE) VALUES (503,'Brainsphere','8213 Clyde Gallagher Crossing','Asheville','North Carolina',28815,'828-113-8262');
INSERT INTO ZOO_CONTRACTORS(CONTRACTOR_ID,CONTRACTOR_NAME,CONTRACTOR_ADDRESS,CONTRACTOR_CITY,CONTRACTOR_STATE,CONTRACTOR_ZIP,CONTRACTOR_PHONE) VALUES (504,'Fliptune','02154 Arkansas Way','Toledo','Ohio',43635,'419-832-4576');
INSERT INTO ZOO_CONTRACTORS(CONTRACTOR_ID,CONTRACTOR_NAME,CONTRACTOR_ADDRESS,CONTRACTOR_CITY,CONTRACTOR_STATE,CONTRACTOR_ZIP,CONTRACTOR_PHONE) VALUES (505,'Thoughtstorm','06 Ronald Regan Way','Akron','Ohio',44321,'330-554-5929');
