CREATE TABLE ZOO_BUILDING(
   BUILDING_ID     NUMBER (3, 0) NOT NULL
  ,BUILDING_NAME   VARCHAR(23) NOT NULL
  ,BUILDING_SPONOR VARCHAR(46) NOT NULL
  ,ENCLOSURES      NUMBER (3, 0)
  ,constraint building_id_pk PRIMARY KEY (building_id)
);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (1,'Building Building One','Building Amkor Technology, Inc.',302);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (2,'Building Building Two','Building ArcBest Corporation',305);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (3,'Building Building Three','Building BioAmber Inc.',303);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (4,'Building Building Four','Building Neos Therapeutics, Inc.',301);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (5,'Building Building Five','Building Sasol Ltd.',NULL);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (6,'Building Building Six','Building Endologix, Inc.',NULL);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (7,'Building Building Seven','Building Chemed Corp.',NULL);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (8,'Building Building Eight','Building Layne Christensen Company',306);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (9,'Building Building Nine','Building Och-Ziff Capital Management Group LLC',NULL);
INSERT INTO ZOO_BUILDING(BUILDING_ID,BUILDING_NAME,BUILDING_SPONOR,ENCLOSURES) VALUES (10,'Building Building Ten','Building DCT Industrial Trust Inc',304);
